platform :ios, '10.0'

use_frameworks!

target 'IPDatePicker_Example' do
  pod 'IPDatePicker', :path => '../'

  target 'IPDatePicker_Tests' do
    inherit! :search_paths

    pod 'Intrepid', '~> 0.12'
  end
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
