platform :ios, '10.0'

use_frameworks!

target 'IPDatePicker_Example' do
  pod 'IPDatePicker', :path => '../'

  target 'IPDatePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'Intrepid', '~> 0.8'
  end
end
